console.log('123');
const FRAGMENT = document.createDocumentFragment();
let variables = {
   category:[
    {
    wrap_name:"category_wrap",
    title: "Action",
    imageLink: "/assets/images/category/action_category.png",
    alt: 'dog in a cap',
    data_id: "action",
    attribute_name: "action",     
    },
    {
        wrap_name:"category_wrap",
        title: "Animals",
        imageLink: "/assets/images/category/animals_category.png",
        alt: 'cat in a shell',
        attribute_name: "animals",    
    },
    {wrap_name:"category_wrap",
        title: "Birds",
        imageLink: "/assets/images/category/birds_category.png",
        alt: 'bird on branch',
        attribute_name: "birds",    
    },
    {wrap_name:"category_wrap",
        title: "Cloth",        
        imageLink: "/assets/images/category/cloth_category.png",
        alt: 'sweater',
        attribute_name: "cloth",    
    },
    {wrap_name:"category_wrap",
        title: "Emotions",
        alt: 'happy dog',
        imageLink: "/assets/images/category/emotions_category.png",
        attribute_name: "emotions",    
    },
    {wrap_name:"category_wrap",
        title: "Hobby",
        alt: 'singing cat',
        imageLink: "/assets/images/category/hobby_category.png",
        attribute_name: "hobby",    
    },
    {wrap_name:"category_wrap",
        title: "Pets",
        imageLink: "/assets/images/category/pets_category.png",
        alt: 'man and cat',
        attribute_name: "pets",    
    },
    {wrap_name:"category_wrap",
        title: "Sport",
        imageLink: "/assets/images/category/sport_category.png",
        alt: 'cat and ball',
        attribute:'data_id',
        attribute_name: "sport",    
    },
],
action:[
    {
    wrap_name:"category_wrap",
    title: "Cry",
    titleRu:"Плакать",
    imageLink: "/assets/images/action/cry.png",
    alt: 'girl crying',    
    attribute_name: "cry",     
    },
    {
        wrap_name:"category_wrap",
        title: "Fly",
        titleRu:"Летать",
        imageLink: "/assets/images/action/fly.png",
        alt: 'duck fly',
        attribute_name: "fly",    
    },
    {wrap_name:"category_wrap",
        title: "hug",
        titleRu:"Обнимать",
        imageLink: "/assets/images/action/hug.png",
        alt: 'girl hug bear',
        attribute_name: "hug",    
    },
    {wrap_name:"category_wrap",
        title: "jump",
        titleRu:"Прыгать",      
        imageLink: "/assets/images/action/jump.png",
        alt: 'kids jump',
        attribute_name: "jump",    
    },
    {wrap_name:"category_wrap",
    title: "laugh",
    titleRu:"смеяться", 
        alt: 'women laugh',
        imageLink: "/assets/images/action/laugh.png",
        attribute_name: "laugh",    
    },
    {wrap_name:"category_wrap",
        title: "open",
        titleRu:"открывать", 
        alt: 'kid open door',
        imageLink: "/assets/images/action/open.png",
        attribute_name: "open",    
    },
    {wrap_name:"category_wrap",
        title: "point",
        titleRu:"указывать", 
        imageLink: "/assets/images/action/point.png",
        alt: 'girl pointing her finger',
        attribute_name: "point",    
    },
    {wrap_name:"category_wrap",
        title: "smile",
        titleRu:"улыбаться", 
        imageLink: "/assets/images/action/smile.png",
        alt: 'girl smile',        
        attribute_name: "smile",    
    },
],
animals:[
    {
    wrap_name:"category_wrap",
    title: "bear",
    titleRu:"медведь",
    imageLink: "/assets/images/animals/bear.png",
    alt: 'bear',    
    attribute_name: "bear",     
    },
    {
        wrap_name:"category_wrap",
        title: "dolphin",
        titleRu:"дельфин",
        imageLink: "/assets/images/animals/dolphin.png",
        alt: 'dolphin',
        attribute_name: "dolphin",    
    },
    {wrap_name:"category_wrap",
        title: "elephant",
        titleRu:"слон",
        imageLink: "/assets/images/animals/elephant.png",
        alt: 'elephant',
        attribute_name: "elephant",    
    },
    {wrap_name:"category_wrap",
        title: "frog",
        titleRu:"лягушка",      
        imageLink: "/assets/images/animals/frog.png",
        alt: 'frog',
        attribute_name: "frog",    
    },
    {wrap_name:"category_wrap",
    title: "giraffe",
    titleRu:"жираф", 
        alt: 'giraffe',
        imageLink: "/assets/images/animals/giraffe.png",
        attribute_name: "giraffe",    
    },
    {wrap_name:"category_wrap",
        title: "lion",
        titleRu:"открывать", 
        alt: 'lion',
        imageLink: "/assets/images/animals/lion.png",
        attribute_name: "lion",    
    },
    {wrap_name:"category_wrap",
        title: "pig",
        titleRu:"свинья", 
        imageLink: "/assets/images/animals/pig.png",
        alt: 'pig',
        attribute_name: "pig",    
    },
    {wrap_name:"category_wrap",
        title: "wolf",
        titleRu:"волк", 
        imageLink: "/assets/images/animals/wolf.png",
        alt: 'wolf',        
        attribute_name: "wolf",    
    },
],
birds:[
    {
    wrap_name:"category_wrap",
    title: "chick",
    titleRu:"цыпленок",
    imageLink: "/assets/images/birds/chick.png",
    alt: 'chick',    
    attribute_name: "chick",     
    },
    {
        wrap_name:"category_wrap",
        title: "chicken",
        titleRu:"курица",
        imageLink: "/assets/images/birds/chicken.png",
        alt: 'chicken',
        attribute_name: "chicken",    
    },
    {wrap_name:"category_wrap",
        title: "flamingos",
        titleRu:"фламинго",
        imageLink: "/assets/images/birds/flamingos.png",
        alt: 'flamingos',
        attribute_name: "flamingos",    
    },
    {wrap_name:"category_wrap",
        title: "owl",
        titleRu:"сова",      
        imageLink: "/assets/images/birds/owl.png",
        alt: 'owl',
        attribute_name: "owl",    
    },
    {wrap_name:"category_wrap",
    title: "parrot",
    titleRu:"попугай", 
        alt: 'parrot',
        imageLink: "/assets/images/birds/parrot.png",
        attribute_name: "parrot",    
    },
    {wrap_name:"category_wrap",
        title: "pigeon",
        titleRu:"голубь", 
        alt: 'pigeon',
        imageLink: "/assets/images/birds/pigeon.png",
        attribute_name: "pigeon",    
    },
    {wrap_name:"category_wrap",
        title: "raven",
        titleRu:"ворон", 
        imageLink: "/assets/images/birds/raven.png",
        alt: 'raven',
        attribute_name: "raven",    
    },
    {wrap_name:"category_wrap",
        title: "tit",
        titleRu:"синица", 
        imageLink: "/assets/images/birds/tit.png",
        alt: 'tit',        
        attribute_name: "tit",    
    },
],
cloth:[
    {
    wrap_name:"category_wrap",
    title: "blouse",
    titleRu:"блузка",
    imageLink: "/assets/images/cloth/blouse.png",
    alt: 'blouse',    
    attribute_name: "blouse",     
    },
    {
        wrap_name:"category_wrap",
        title: "boot",
        titleRu:"ботинок",
        imageLink: "/assets/images/cloth/boot.png",
        alt: 'boot',
        attribute_name: "boot",    
    },
    {wrap_name:"category_wrap",
        title: "coat",
        titleRu:"пальто",
        imageLink: "/assets/images/cloth/coat.png",
        alt: 'coat',
        attribute_name: "coat",    
    },
    {wrap_name:"category_wrap",
        title: "dress",
        titleRu:"платье",      
        imageLink: "/assets/images/cloth/dress.png",
        alt: 'dress',
        attribute_name: "dress",    
    },
    {wrap_name:"category_wrap",
    title: "pants",
    titleRu:"брюки", 
        alt: 'pants',
        imageLink: "/assets/images/cloth/pants.png",
        attribute_name: "pants",    
    },
    {wrap_name:"category_wrap",
        title: "shirt",
        titleRu:"рубашка", 
        alt: 'shirt',
        imageLink: "/assets/images/cloth/shirt.png",
        attribute_name: "shirt",    
    },
    {wrap_name:"category_wrap",
        title: "shoe",
        titleRu:"обувь", 
        imageLink: "/assets/images/cloth/shoe.png",
        alt: 'shoe',
        attribute_name: "shoe",    
    },
    {wrap_name:"category_wrap",
        title: "skirt",
        titleRu:"юбка", 
        imageLink: "/assets/images/cloth/skirt.png",
        alt: 'skirt',        
        attribute_name: "skirt",    
    },
],
emotions:[
    {
    wrap_name:"category_wrap",
    title: "angry",
    titleRu:"злой",
    imageLink: "/assets/images/emotions/angry.png",
    alt: 'angry',    
    attribute_name: "angry",     
    },
    {
        wrap_name:"category_wrap",
        title: "happy",
        titleRu:"счастливый",
        imageLink: "/assets/images/emotions/happy.png",
        alt: 'happy',
        attribute_name: "happy",    
    },
    {wrap_name:"category_wrap",
        title: "pride",
        titleRu:"гордый",
        imageLink: "/assets/images/emotions/pride.png",
        alt: 'pride',
        attribute_name: "pride",    
    },
    {wrap_name:"category_wrap",
        title: "sad",
        titleRu:"грустный",      
        imageLink: "/assets/images/emotions/sad.png",
        alt: 'sad',
        attribute_name: "sad",    
    },
    {wrap_name:"category_wrap",
    title: "scared",
    titleRu:"испуганный", 
        alt: 'scared',
        imageLink: "/assets/images/emotions/scared.png",
        attribute_name: "scared",    
    },
    {wrap_name:"category_wrap",
        title: "surprised",
        titleRu:"удивленный", 
        alt: 'surprised',
        imageLink: "/assets/images/emotions/surprised.png",
        attribute_name: "surprised",    
    },
    {wrap_name:"category_wrap",
        title: "tired",
        titleRu:"уставший", 
        imageLink: "/assets/images/emotions/tired.png",
        alt: 'tired',
        attribute_name: "tired",    
    },
    {wrap_name:"category_wrap",
        title: "worried",
        titleRu:"обеспокоенный", 
        imageLink: "/assets/images/emotions/worried.png",
        alt: 'worried',        
        attribute_name: "worried",    
    },
],
hobby:[
    {
    wrap_name:"category_wrap",
    title: "coding",
    titleRu:"программирование",
    imageLink: "/assets/images/hobby/coding.png",
    alt: 'coding',    
    attribute_name: "coding",     
    },
    {
        wrap_name:"category_wrap",
        title: "dance",
        titleRu:"танцевать",
        imageLink: "/assets/images/hobby/dance.png",
        alt: 'girl and boy dancing',
        attribute_name: "dance",    
    },
    {wrap_name:"category_wrap",
        title: "draw",
        titleRu:"рисовать",
        imageLink: "/assets/images/hobby/draw.png",
        alt: 'girl drawing',
        attribute_name: "draw",    
    },
    {wrap_name:"category_wrap",
        title: "photography",
        titleRu:"фотографировать",      
        imageLink: "/assets/images/hobby/photography.png",
        alt: 'girl takes photo',
        attribute_name: "photography",    
    },
    {wrap_name:"category_wrap",
    title: "play",
    titleRu:"играть", 
        alt: 'kids playing',
        imageLink: "/assets/images/hobby/play.png",
        attribute_name: "play",    
    },
    {wrap_name:"category_wrap",
        title: "read",
        titleRu:"читать", 
        alt: 'children reading book',
        imageLink: "/assets/images/hobby/reading.png",
        attribute_name: "reading",    
    },
    {wrap_name:"category_wrap",
        title: "sing",
        titleRu:"петь", 
        imageLink: "/assets/images/hobby/sing.png",
        alt: 'girl is singing',
        attribute_name: "sing",    
    },
    {wrap_name:"category_wrap",
        title: "travel",
        titleRu:"путешествовать", 
        imageLink: "/assets/images/hobby/travel.png",
        alt: 'boy lies on the suitcase',        
        attribute_name: "travel",    
    },
],
pets:[
    {
    wrap_name:"category_wrap",
    title: "cat",
    titleRu:"кот",
    imageLink: "/assets/images/pets/cat.png",
    alt: 'cat',    
    attribute_name: "cat",     
    },
    {
        wrap_name:"category_wrap",
        title: "dog",
        titleRu:"собака",
        imageLink: "/assets/images/pets/dog.png",
        alt: 'dog',
        attribute_name: "dog",    
    },
    {wrap_name:"category_wrap",
        title: "fish",
        titleRu:"рыба",
        imageLink: "/assets/images/pets/fish.png",
        alt: 'fish',
        attribute_name: "fish",    
    },
    {wrap_name:"category_wrap",
        title: "horse",
        titleRu:"лошадь",      
        imageLink: "/assets/images/pets/horse.png",
        alt: 'horse',
        attribute_name: "horse",    
    },
    {wrap_name:"category_wrap",
    title: "mouse",
    titleRu:"мышь", 
        alt: 'mouse',
        imageLink: "/assets/images/pets/mouse.png",
        attribute_name: "mouse",    
    },
    {wrap_name:"category_wrap",
        title: "rabbit",
        titleRu:"кролик", 
        alt: 'rabbit',
        imageLink: "/assets/images/pets/rabbit.png",
        attribute_name: "rabbit",    
    },
    {wrap_name:"category_wrap",
        title: "sheep",
        titleRu:"овца", 
        imageLink: "/assets/images/pets/sheep.png",
        alt: 'sheep',
        attribute_name: "sheep",    
    },
    {wrap_name:"category_wrap",
        title: "turtle",
        titleRu:"черепаха", 
        imageLink: "/assets/images/pets/turtle.png",
        alt: 'turtle',        
        attribute_name: "turtle",    
    },
],
sport:[
    {
    wrap_name:"category_wrap",
    title: "dive",
    titleRu:"нырять",
    imageLink: "/assets/images/sport/cat.png",
    alt: 'dive',    
    attribute_name: "dive",     
    },
    {
        wrap_name:"category_wrap",
        title: "fish",
        titleRu:"рыбачить",
        imageLink: "/assets/images/sport/fish.png",
        alt: 'fish',
        attribute_name: "fish",    
    },
    {wrap_name:"category_wrap",
        title: "ride",
        titleRu:"ездить",
        imageLink: "/assets/images/sport/ride.png",
        alt: 'ride',
        attribute_name: "ride",    
    },
    {wrap_name:"category_wrap",
        title: "run",
        titleRu:"бегать",      
        imageLink: "/assets/images/sport/run.png",
        alt: 'run',
        attribute_name: "run",    
    },
    {wrap_name:"category_wrap",
    title: "skating",
    titleRu:"катание на коньках", 
        alt: 'skating',
        imageLink: "/assets/images/sport/skating.png",
        attribute_name: "skating",    
    },
    {wrap_name:"category_wrap",
        title: "skiing",
        titleRu:"кататься на сноуборде", 
        alt: 'skiing',
        imageLink: "/assets/images/sport/skiing.png",
        attribute_name: "skiing",    
    },
    {wrap_name:"category_wrap",
        title: "skip",
        titleRu:"прыгать на скакалке", 
        imageLink: "/assets/images/sport/skip.png",
        alt: 'skip',
        attribute_name: "skip",    
    },
    {wrap_name:"category_wrap",
        title: "swim",
        titleRu:"плавать", 
        imageLink: "/assets/images/sport/swim.png",
        alt: 'swim',        
        attribute_name: "swim",    
    },
],
}

function createCard (value){
    let content = document.querySelector('.content');    
    value.forEach((element)=>{
        let wrap_name = element.wrap_name;
        // console.log(wrap_name)
        let attribute_name = element.attribute_name;
        let imageLink = element.imageLink;
        let alt = element.alt;
        let divCard = createElement(wrap_name,attribute_name,imageLink,alt);
        // console.log(divCard)
        FRAGMENT.append(divCard);

    })
    content.prepend(FRAGMENT);
}

function createElement (wrap_name,attribute_name,imageLink,alt){
    let wrap = document.createElement('div');
    wrap.classList.add(wrap_name);
    wrap.dataset.id = attribute_name;
    let imgWrap = document.createElement('div');
    imgWrap.classList.add('img_wrap');
    let img = document.createElement('img'); 
    img.setAttribute('src',imageLink);
    img.setAttribute('alt',alt);
    imgWrap.append(img);
    let title = document.createElement('h3');
    title.innerText = attribute_name;
    
    wrap.append(imgWrap);
    wrap.append(title);
    return wrap;    
}
createCard(variables.category)